"""Pydantic schemas for Monitoring / Anomaly Detection API."""

from __future__ import annotations

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Request Schemas
# ---------------------------------------------------------------------------

class DetectionFrameRequest(BaseModel):
    """Request body for POST /monitoring/event — a single detection frame."""

    session_id: str = Field(description="Active exam session UUID.")
    candidate_id: str = Field(description="Candidate UUID.")
    face_count: int = Field(default=1, ge=0, description="Number of faces detected in frame.")
    gaze_yaw: float | None = Field(default=None, description="Horizontal gaze angle in degrees from center.")
    gaze_pitch: float | None = Field(default=None, description="Vertical gaze angle in degrees from center.")
    camera_active: bool = Field(default=True, description="Whether the webcam is producing frames.")
    answer_changes_last_30s: int = Field(default=0, ge=0, description="Answer changes in the last 30 seconds.")
    timestamp: str = Field(default="", description="ISO 8601 timestamp from client.")


# ---------------------------------------------------------------------------
# Response Schemas
# ---------------------------------------------------------------------------

class SecurityAlertResponse(BaseModel):
    """A single alert generated by the rule engine."""

    alert_type: str
    severity: str
    details: dict
    evidence_hash: str


class DetectionResultResponse(BaseModel):
    """Response for POST /monitoring/event."""

    alerts_generated: int
    alerts: list[SecurityAlertResponse]
    message: str


class SecurityEventResponse(BaseModel):
    """Persisted security event returned from queries."""

    id: str
    session_id: str
    candidate_id: str
    event_type: str
    severity: str
    details: str  # JSON string
    evidence_hash: str
    acknowledged: bool
    created_at: str

    model_config = {"from_attributes": True}


class EventListResponse(BaseModel):
    """Paginated list of security events."""

    events: list[SecurityEventResponse]
    total: int
    page: int
    page_size: int


class SessionSummaryResponse(BaseModel):
    """Anomaly summary for a specific exam session."""

    session_id: str
    total_events: int
    high_count: int
    medium_count: int
    low_count: int
    event_types: dict[str, int]  # {MULTIPLE_FACES: 3, NO_FACE: 1, ...}
