/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00288e",
        "primary-container": "#1e40af",
        "on-primary": "#ffffff",
        "on-primary-container": "#a8b8ff",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        "inverse-primary": "#b8c4ff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c4ff",
        "secondary": "#545f73",
        "on-secondary": "#ffffff",
        "secondary-container": "#d5e0f8",
        "on-secondary-container": "#586377",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary": "#440098",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5f00d1",
        "on-tertiary-container": "#c9aeff",
        "on-tertiary-fixed": "#25005a",
        "on-tertiary-fixed-variant": "#5a00c6",
        "tertiary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#d2bbff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#444653",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#3755c3",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "outline": "#757684",
        "outline-variant": "#c4c5d5",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "240px",
        "topbar-height": "64px",
        "container-padding": "24px",
        "card-padding": "16px",
        "gutter": "16px",
      },
      fontFamily: {
        "body": ["Inter", "sans-serif"],
        "page-title": ["Inter", "sans-serif"],
        "section-header": ["Inter", "sans-serif"],
        "label-medium": ["Inter", "sans-serif"],
        "micro": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "page-title": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "section-header": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-medium": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "micro": ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
